export const categories = [{
  color: '#587BE0',
  background: '#EAEFFF',
  label: 'Exchanges',
  icon: 'exchange.svg',
}, {
  color: '#414047',
  background: '#F5F5F5',
  label: 'Games',
  icon: 'games.svg',
}, {
  color: '#34AE91',
  background: '#E2F9F3',
  label: 'Marketplaces',
  icon: 'marketplaces.svg',
}, {
  color: '#F98F54',
  background: '#FFF3EC',
  label: 'Defi',
  icon: 'defi.svg',
}, {
  color: '#54AAF9',
  background: '#EBF5FF',
  label: 'Collectibles',
  icon: 'collectibles.svg',
}, {
  color: '#885FFF',
  background: '#F0EBFF',
  label: 'Utilities',
  icon: 'utilities.svg',
}]
